### ISSUE TITLE
Número de colaboradores

### ISSUE THREAD

**Issue by lauramcastro** [Xokage/practica-vvs-4malladores#1]
Un dos catro membros do equipo non fixo aínda ningunha contribución.

**Comment by kermititan** [comment]
Non sabemos por qué non aparece como colaborador Francisco Pais Fondo, xa que si que realizou contribucións..
Ver:
https://github.com/Xokage/practica-vvs-4malladores/commit/61e4aec89e9cd03d82b72f670ad772a3675ffb93
https://github.com/Xokage/practica-vvs-4malladores/commit/21c428b03e61ff50eb18521b694e2083191d6ffc
https://github.com/Xokage/practica-vvs-4malladores/commit/61434d9bd0e31e1e25ca7e8bdd0061d4a88ef13a
https://github.com/Xokage/practica-vvs-4malladores/commit/87a7af5f89baf70008c618e1c1cc50e8c9fbcde8
https://github.com/Xokage/practica-vvs-4malladores/commit/b90fb2b7b9ddd5ef5c802a1f4eb0d65da3e7cd40

Para máis información comprobar commits.
https://github.com/Xokage/practica-vvs-4malladores/commits/master

**Comment by lauramcastro** [comment]
Francisco Pais Fondo é @fran464646 ?

**Comment by kermititan** [comment]
Si, pero non sei por qué non nos aparecían os cambios del. En canto quedemos imos revisalo a ver se o solucionamos.

**Comment by kermititan** [comment]
O problema era que tanto @fran464646 como @martinquinteiro fixeron os commits usando o correo da udc, mentres que rexistraron a conta cun correo diferente, por iso non aparecían como colaboradores.
Aínda que seguen aparecendo "3 contribuíntes" unha vez pinchas ahí xa se ve que somos 4 persoas e o que fixemos os 4.
Grazas por avisar do problema.
