### ISSUE TITLE
Non hai documentación.

### ISSUE THREAD

**Issue by lauramcastro** [Xokage/practica-vvs-4malladores#2]
O proxecto non inclúe documentación: non hai comentarios en JavaDoc no código fonte, e tampouco hai ningún diagrama UML que represente a estrutura actual da implementación (a evolución do diagrama do enunciado).

**Comment by martinquinteiro** [comment]
Añadida a documentación requerida (diagrama de clases UML e JavaDoc) e modificado o Readme.
