### ISSUE TITLE
Búsqueda en Anuncio y Canción

### ISSUE THREAD

**Issue by alejandrofortes** [Xokage/practica-vvs-4malladores#4]
Al realizar la búsqueda se debe devolver la canción o el anuncio que contenga ese string y no que sea idéntico al mismo

**Comment by cristiancanosa** [comment]
Solucionado, pero no devuelve solo una Cancion o un Anuncio sino una List de tipo Contenido tal y como indica la especificación.

**Comment by alejandrofortes** [comment]
Si, quería decir lista de tipo contenido, no una canción o anuncio. Fallo mío
