### ISSUE TITLE
Contructor de ServidorSimpleImp

### ISSUE THREAD

**Issue by angelGarciaSantos** [Xokage/practica-vvs-4malladores#5]
¿Por qué en el constructor de ServidorSimpleImp se añade un token valido a la lista tokenValido?

**Comment by kermititan** [comment]
Por si se quiere instanciar un ServidorSimpleImp con un token valido <strong> concreto </strong> en la lista de tokenValido, ya que el generador de tokens genera un token aleatorio.

**Comment by alejandrofortes** [comment]
Vale, entendido. A verdade e que ten moito sentido.
