### ISSUE TITLE
Uso de constantes

### ISSUE THREAD

**Issue by alejandrofortes** [Xokage/practica-vvs-4malladores#6]
Para valores que se usen en múltiples ocasiones es mejor crear constantes, ya que si es necesario modificar ese valor habŕia que hacerlo en todos los sitios en que se use.

Por ejemplo, en ServidorSimpleImp usais el valor 10 (que representa el número máximo de contenidos que se pueden devolver antes de que caduque) en varios sitios. Si queremos hacer que el token caduque cada 20 contenidos, habŕia que hacer varios cambios.

**Comment by kermititan** [comment]
Grazas polo aviso. Solucionado.
