### ISSUE TITLE
Nombres confusos en variables.

### ISSUE THREAD

**Issue by angelGarciaSantos** [Xokage/practica-vvs-4malladores#7]
El nombre **tokenContenido** es un poco confuso, quizá sería mejor llamarlo **tokenMaestro**.
La lista **tokenValido** quizá sería más correcto llamarla **tokensValidos**, ya que puede contener más de un token.

**Comment by martinquinteiro** [comment]
Gracias por la sugerencia del uso de nombres nemotécnicos. Se corregirán para la siguiente release.
