### ISSUE TITLE
Eliminacion de tests superfluos

### ISSUE THREAD

**Issue by alejandrofortes** [Xokage/practica-vvs-4malladores#9]
Eliminar los tests que sirvan para nada. Concretamente el test _TravisTest_

**Comment by kermititan** [comment]
Realmente o <i>TravisTest</i> servía para algo, concretamente para probar a CI en Travis cando aínda non tiñamos tests, pero agora non serve para nada, que creo que é ao que te queres referir cando suxires que o test <i>TravisTest</i> sirve para nada. Tendo en conta que o resto dos tests realmente si serven para algo antes, ao non servir para nada, o <i>TravisTest</i> era necesario como placeholder, polo que agora a súa mera existencia non ten sentido. :trollface: 

TL;DR: Quitamos o test.

**Comment by martinquinteiro** [comment]
Eliminado test! Se incluirá en la siguiente release.

**Comment by alejandrofortes** [comment]
Si, pode que non me expresara ben. Quería decir que dado que o uso inicial do test (probar que Travis funcionase) xa estaba cuberto polas novas probas, este test pasaba a ser innnecesario.

PD: Coidarei as palabras que escolla no futuro :)

**Comment by lauramcastro** [comment]
:+1: 

@Xokage o TL;DR normalmente pónse ao principio do comentario ;-)
